/**
 * Projet JDofusCalc
 * 
 * Copyright PAPAYA Alexandre, (2008, 2009) 
 * 
 * alexandre.papaya@gmail.com
 * 
 * Ce logiciel est un programme informatique servant à gérer les personnages
 * de l'utilisateur sur le jeu Dofus(c) et à calculer et tester les répercutions
 * sur le jeu de la modification de divers paramètres tels que les équipements,
 * les caractéristiques, ect. Ce programme est codé en java et utilise des
 * bibliothèques dont les licences sont compatibles avec la licence CeCILL.
 * 
 * Ce logiciel est régi par la licence CeCILL soumise au droit français et
 * respectant les principes de diffusion des logiciels libres. Vous pouvez
 * utiliser, modifier et/ou redistribuer ce programme sous les conditions
 * de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA 
 * sur le site "http://www.cecill.info".
 * 
 * En contrepartie de l'accessibilité au code source et des droits de copie,
 * de modification et de redistribution accordés par cette licence, il n'est
 * offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
 * seule une responsabilité restreinte pèse sur l'auteur du programme,  le
 * titulaire des droits patrimoniaux et les concédants successifs.
 * 
 * A cet égard  l'attention de l'utilisateur est attirée sur les risques
 * associés au chargement,  à l'utilisation,  à la modification et/ou au
 * développement et à la reproduction du logiciel par l'utilisateur étant 
 * donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
 * manipuler et qui le réserve donc à des développeurs et des professionnels
 * avertis possédant  des  connaissances  informatiques approfondies.  Les
 * utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
 * logiciel à leurs besoins dans des conditions permettant d'assurer la
 * sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
 * à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 
 * 
 * Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
 * pris connaissance de la licence CeCILL, et que vous en avez accepté les
 * termes.
 */
package org.JDofusCalc.outils.aspirateurs;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import org.JDofusCalc.dofus.autres.Classe;
import org.JDofusCalc.dofus.autres.Degats;
import org.JDofusCalc.dofus.autres.Sort;
import org.JDofusCalc.dofus.autres.Degats.FlagsTypesDegats;
import org.jdom.Document;
import org.jdom.Element;
import org.jdom.output.Format;
import org.jdom.output.XMLOutputter;

import fr.ayapap.ASQL;
import fr.ayapap.ASQLRequete;

/**
 * TODO
 *
 * @author PAPAYA Alexandre
 * @category TODO
 * @version 1.0
 */
public class FichierSorts
{
	/**
	 * Connexion à la base de données.
	 */
	protected ASQL bdd = null;

	/**
	 * @param args
	 */
	public static void main(String[] args)
	{
		/*new FichierSorts(0, "all");
		new FichierSorts(1, "crâ");
		new FichierSorts(2, "ecaflip");
		new FichierSorts(3, "eniripsa");
		new FichierSorts(4, "enutrof");
		new FichierSorts(5, "féca");
		new FichierSorts(6, "xélor");
		new FichierSorts(7, "iop");
		new FichierSorts(8, "osamodas");
		new FichierSorts(9, "pandawa");
		new FichierSorts(10, "sacrieur");
		new FichierSorts(11, "sadida");
		new FichierSorts(12, "sram");*/
	}

	/**
	 * TODO
	 * 
	 * @category Constructeur
	 */
	public FichierSorts(int idClasse, String nomClasse)
	{
		try
		{
			// Initialisation de la connexion à la basse de données
			this.bdd = new ASQL("org.h2.Driver", "h2:file:donnees/dofusdatabase", "dofusdatabase", "Administrateur", "admin");

			Document fichierXML = new Document();
			Element root = new Element("sorts");
			fichierXML.setRootElement(root);
			
			ArrayList<Sort> sorts = this.getSorts(idClasse);
			for(int i = 0; i < sorts.size(); i++)
			{
				Sort sort = sorts.get(i);
				System.out.println(sort.getNom());
				Element eleSort = new Element("sort");
				
				// Nom du sort
				Element eleNom = new Element("nom");
				eleNom.setText(sort.getNom());
				eleSort.addContent(eleNom);
				// Niveau du sort
				Element eleNiveau = new Element("niveau");
				eleNiveau.setText("0");
				eleSort.addContent(eleNiveau);
				
				
				for(int y = 1; y <= 6; y++)
				{
					Element eleCaracteristique = new Element("caracteristiques");
					eleCaracteristique.setAttribute("niveau", String.valueOf(y));
					
					// PA
					Element elePa = new Element("pa");
					elePa.setText(String.valueOf(sort.get(y, "PA")));
					eleCaracteristique.addContent(elePa);
					// CC
					Element eleCC = new Element("cc");
					eleCC.setText(String.valueOf(sort.get(y, "CC")));
					eleCaracteristique.addContent(eleCC);
					// EC
					Element eleEC = new Element("ec");
					eleEC.setText(String.valueOf(sort.get(y, "EC")));
					eleCaracteristique.addContent(eleEC);
					
					// Clefs
					String[] clefs = new String[] {"Dégâts neutre", "Dégâts terre", "Dégâts feu", "Dégâts eau", "Dégâts air", "Soins", "Vols de vie neutre", "Vols de vie terre", "Vols de vie feu", "Vols de vie eau", "Vols de vie air"};
					
					/* Normal */
					Degats degatsNormaux = (Degats) sort.get(y, "Degats");
					Element eleNormal = new Element("normal");
					// Effets
					Element eleEffets = new Element("effets");
					eleEffets.setText("");
					eleNormal.addContent(eleEffets);
					// Degats
					for(String clef : clefs)
					{
						int degatsMin = degatsNormaux.get(FlagsTypesDegats.getFlag(clef + " minimums"));
						int degatsMax = degatsNormaux.get(FlagsTypesDegats.getFlag(clef + " maximums"));
						if(degatsMax != 0)
						{
							Element eleDegatsNormaux = new Element("degats");
							eleDegatsNormaux.setAttribute("type", clef);
							Element eleDegatsNormauxMin = new Element("min");
							eleDegatsNormauxMin.setText(String.valueOf(degatsMin));
							eleDegatsNormaux.addContent(eleDegatsNormauxMin);
							Element eleDegatsNormauxMax = new Element("max");
							eleDegatsNormauxMax.setText(String.valueOf(degatsMax));
							eleDegatsNormaux.addContent(eleDegatsNormauxMax);
							eleNormal.addContent(eleDegatsNormaux);
						}
					}
					eleCaracteristique.addContent(eleNormal);
					
					/* Critiques */
					if(!sort.get(y, "CC").equals("0"))
					{
						Degats degatsCC = (Degats) sort.get(y, "DegatsCC");
						Element eleCritique = new Element("critique");
						// Effets
						Element eleEffetsCC = new Element("effets");
						eleEffetsCC.setText("");
						eleCritique.addContent(eleEffetsCC);
						// Degats
						for(String clef : clefs)
						{
							int degatsMin = degatsCC.get(FlagsTypesDegats.getFlag(clef + " Minimum"));
							int degatsMax = degatsCC.get(FlagsTypesDegats.getFlag(clef + " Maximum"));
							if(degatsMax != 0)
							{
								Element eleDegatsCritiques = new Element("degats");
								eleDegatsCritiques.setAttribute("type", clef);
								Element eleDegatsCritiquesMin = new Element("min");
								eleDegatsCritiquesMin.setText(String.valueOf(degatsMin));
								eleDegatsCritiques.addContent(eleDegatsCritiquesMin);
								Element eleDegatsCritiquesMax = new Element("max");
								eleDegatsCritiquesMax.setText(String.valueOf(degatsMax));
								eleDegatsCritiques.addContent(eleDegatsCritiquesMax);
								eleCritique.addContent(eleDegatsCritiques);
							}
						}
						eleCaracteristique.addContent(eleCritique);
					}
					eleSort.addContent(eleCaracteristique);
				}
				root.addContent(eleSort);
			}

			Format format = Format.getPrettyFormat();
			format.setIndent("\t");
			XMLOutputter out = new XMLOutputter(format);
			
			File fichier = new File("dofusdatabase/" + nomClasse + "_sorts.xml");
			FileOutputStream fileOutput = new FileOutputStream(fichier);
			out.output(fichierXML, fileOutput);
		    //out.output(fichierXML, System.out);
			
			System.out.println("Fichier " + fichier.getPath() + " créé.");
		}
		catch(IOException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	/**
	 * Renvoie la liste des sorts de la classe {@code classe}.
	 * 
	 * @param classe - La classe.
	 * @return Une {@code ArrayList} des sort.
	 */
	public ArrayList<Sort> getSorts(int classe)
	{
		try
		{
			ArrayList<Sort> sorts = new ArrayList<Sort>();

			ASQLRequete req = this.bdd.requete("SELECT S.ID AS S_ID, S.NOM AS S_NOM, S.NIVEAU AS S_NIVEAU, S.CLASSE AS S_CLASSE, S.NATURE AS S_NATURE, S.NIVEAU_1 AS S_NIVEAU_1, S.NIVEAU_2 AS S_NIVEAU_2, S.NIVEAU_3 AS S_NIVEAU_3, S.NIVEAU_4 AS S_NIVEAU_4, S.NIVEAU_5 AS S_NIVEAU_5, S.NIVEAU_6 AS S_NIVEAU_6, " + "N1.ID AS N1_ID, N1.PA AS N1_PA, N1.CC AS N1_CC, N1.EC AS N1_EC, N1.DEGATS AS N1_DEGATS, N1.DEGATS_CC AS N1_DEGATS_CC, N1.EFFETS AS N1_EFFETS, N1.EFFETS_CC AS N1_EFFETS_CC, " + "N2.ID AS N2_ID, N2.PA AS N2_PA, N2.CC AS N2_CC, N2.EC AS N2_EC, N2.DEGATS AS N2_DEGATS, N2.DEGATS_CC AS N2_DEGATS_CC, N2.EFFETS AS N2_EFFETS, N2.EFFETS_CC AS N2_EFFETS_CC, " + "N3.ID AS N3_ID, N3.PA AS N3_PA, N3.CC AS N3_CC, N3.EC AS N3_EC, N3.DEGATS AS N3_DEGATS, N3.DEGATS_CC AS N3_DEGATS_CC, N3.EFFETS AS N3_EFFETS, N3.EFFETS_CC AS N3_EFFETS_CC, " + "N4.ID AS N4_ID, N4.PA AS N4_PA, N4.CC AS N4_CC, N4.EC AS N4_EC, N4.DEGATS AS N4_DEGATS, N4.DEGATS_CC AS N4_DEGATS_CC, N4.EFFETS AS N4_EFFETS, N4.EFFETS_CC AS N4_EFFETS_CC, " + "N5.ID AS N5_ID, N5.PA AS N5_PA, N5.CC AS N5_CC, N5.EC AS N5_EC, N5.DEGATS AS N5_DEGATS, N5.DEGATS_CC AS N5_DEGATS_CC, N5.EFFETS AS N5_EFFETS, N5.EFFETS_CC AS N5_EFFETS_CC, " + "N6.ID AS N6_ID, N6.PA AS N6_PA, N6.CC AS N6_CC, N6.EC AS N6_EC, N6.DEGATS AS N6_DEGATS, N6.DEGATS_CC AS N6_DEGATS_CC, N6.EFFETS AS N6_EFFETS, N6.EFFETS_CC AS N6_EFFETS_CC, " + "DEGN1.ID AS DEGN1_ID, DEGN1.TABLE AS DEGN1_TABLE, DEGN1.CHAMP AS DEGN1_CHAMP, DEGN1.DEGATS_NEUTRE_MINI AS DEGN1_DEGATS_NEUTRE_MINI, DEGN1.DEGATS_NEUTRE_MAXI AS DEGN1_DEGATS_NEUTRE_MAXI, DEGN1.DEGATS_TERRE_MINI AS DEGN1_DEGATS_TERRE_MINI, DEGN1.DEGATS_TERRE_MAXI AS DEGN1_DEGATS_TERRE_MAXI, DEGN1.DEGATS_FEU_MINI AS DEGN1_DEGATS_FEU_MINI, DEGN1.DEGATS_FEU_MAXI AS DEGN1_DEGATS_FEU_MAXI, DEGN1.DEGATS_EAU_MINI AS DEGN1_DEGATS_EAU_MINI, DEGN1.DEGATS_EAU_MAXI AS DEGN1_DEGATS_EAU_MAXI, DEGN1.DEGATS_AIR_MINI AS DEGN1_DEGATS_AIR_MINI, DEGN1.DEGATS_AIR_MAXI AS DEGN1_DEGATS_AIR_MAXI, DEGN1.VOLE_NEUTRE_MINI AS DEGN1_VOLE_NEUTRE_MINI, DEGN1.VOLE_NEUTRE_MAXI AS DEGN1_VOLE_NEUTRE_MAXI, DEGN1.VOLE_TERRE_MINI AS DEGN1_VOLE_TERRE_MINI, DEGN1.VOLE_TERRE_MAXI AS DEGN1_VOLE_TERRE_MAXI, DEGN1.VOLE_FEU_MINI AS DEGN1_VOLE_FEU_MINI, DEGN1.VOLE_FEU_MAXI AS DEGN1_VOLE_FEU_MAXI, DEGN1.VOLE_EAU_MINI AS DEGN1_VOLE_EAU_MINI, DEGN1.VOLE_EAU_MAXI AS DEGN1_VOLE_EAU_MAXI, DEGN1.VOLE_AIR_MINI AS DEGN1_VOLE_AIR_MINI, DEGN1.VOLE_AIR_MAXI AS DEGN1_VOLE_AIR_MAXI, DEGN1.SOINS_MINI AS DEGN1_SOINS_MINI, DEGN1.SOINS_MAXI AS DEGN1_SOINS_MAXI, " + "DEGCCN1.ID AS DEGCCN1_ID, DEGCCN1.TABLE AS DEGCCN1_TABLE, DEGCCN1.CHAMP AS DEGCCN1_CHAMP, DEGCCN1.DEGATS_NEUTRE_MINI AS DEGCCN1_DEGATS_NEUTRE_MINI, DEGCCN1.DEGATS_NEUTRE_MAXI AS DEGCCN1_DEGATS_NEUTRE_MAXI, DEGCCN1.DEGATS_TERRE_MINI AS DEGCCN1_DEGATS_TERRE_MINI, DEGCCN1.DEGATS_TERRE_MAXI AS DEGCCN1_DEGATS_TERRE_MAXI, DEGCCN1.DEGATS_FEU_MINI AS DEGCCN1_DEGATS_FEU_MINI, DEGCCN1.DEGATS_FEU_MAXI AS DEGCCN1_DEGATS_FEU_MAXI, DEGCCN1.DEGATS_EAU_MINI AS DEGCCN1_DEGATS_EAU_MINI, DEGCCN1.DEGATS_EAU_MAXI AS DEGCCN1_DEGATS_EAU_MAXI, DEGCCN1.DEGATS_AIR_MINI AS DEGCCN1_DEGATS_AIR_MINI, DEGCCN1.DEGATS_AIR_MAXI AS DEGCCN1_DEGATS_AIR_MAXI, DEGCCN1.VOLE_NEUTRE_MINI AS DEGCCN1_VOLE_NEUTRE_MINI, DEGCCN1.VOLE_NEUTRE_MAXI AS DEGCCN1_VOLE_NEUTRE_MAXI, DEGCCN1.VOLE_TERRE_MINI AS DEGCCN1_VOLE_TERRE_MINI, DEGCCN1.VOLE_TERRE_MAXI AS DEGCCN1_VOLE_TERRE_MAXI, DEGCCN1.VOLE_FEU_MINI AS DEGCCN1_VOLE_FEU_MINI, DEGCCN1.VOLE_FEU_MAXI AS DEGCCN1_VOLE_FEU_MAXI, DEGCCN1.VOLE_EAU_MINI AS DEGCCN1_VOLE_EAU_MINI, DEGCCN1.VOLE_EAU_MAXI AS DEGCCN1_VOLE_EAU_MAXI, DEGCCN1.VOLE_AIR_MINI AS DEGCCN1_VOLE_AIR_MINI, DEGCCN1.VOLE_AIR_MAXI AS DEGCCN1_VOLE_AIR_MAXI, DEGCCN1.SOINS_MINI AS DEGCCN1_SOINS_MINI, DEGCCN1.SOINS_MAXI AS DEGCCN1_SOINS_MAXI, " + "DEGN2.ID AS DEGN2_ID, DEGN2.TABLE AS DEGN2_TABLE, DEGN2.CHAMP AS DEGN2_CHAMP, DEGN2.DEGATS_NEUTRE_MINI AS DEGN2_DEGATS_NEUTRE_MINI, DEGN2.DEGATS_NEUTRE_MAXI AS DEGN2_DEGATS_NEUTRE_MAXI, DEGN2.DEGATS_TERRE_MINI AS DEGN2_DEGATS_TERRE_MINI, DEGN2.DEGATS_TERRE_MAXI AS DEGN2_DEGATS_TERRE_MAXI, DEGN2.DEGATS_FEU_MINI AS DEGN2_DEGATS_FEU_MINI, DEGN2.DEGATS_FEU_MAXI AS DEGN2_DEGATS_FEU_MAXI, DEGN2.DEGATS_EAU_MINI AS DEGN2_DEGATS_EAU_MINI, DEGN2.DEGATS_EAU_MAXI AS DEGN2_DEGATS_EAU_MAXI, DEGN2.DEGATS_AIR_MINI AS DEGN2_DEGATS_AIR_MINI, DEGN2.DEGATS_AIR_MAXI AS DEGN2_DEGATS_AIR_MAXI, DEGN2.VOLE_NEUTRE_MINI AS DEGN2_VOLE_NEUTRE_MINI, DEGN2.VOLE_NEUTRE_MAXI AS DEGN2_VOLE_NEUTRE_MAXI, DEGN2.VOLE_TERRE_MINI AS DEGN2_VOLE_TERRE_MINI, DEGN2.VOLE_TERRE_MAXI AS DEGN2_VOLE_TERRE_MAXI, DEGN2.VOLE_FEU_MINI AS DEGN2_VOLE_FEU_MINI, DEGN2.VOLE_FEU_MAXI AS DEGN2_VOLE_FEU_MAXI, DEGN2.VOLE_EAU_MINI AS DEGN2_VOLE_EAU_MINI, DEGN2.VOLE_EAU_MAXI AS DEGN2_VOLE_EAU_MAXI, DEGN2.VOLE_AIR_MINI AS DEGN2_VOLE_AIR_MINI, DEGN2.VOLE_AIR_MAXI AS DEGN2_VOLE_AIR_MAXI, DEGN2.SOINS_MINI AS DEGN2_SOINS_MINI, DEGN2.SOINS_MAXI AS DEGN2_SOINS_MAXI, " + "DEGCCN2.ID AS DEGCCN2_ID, DEGCCN2.TABLE AS DEGCCN2_TABLE, DEGCCN2.CHAMP AS DEGCCN2_CHAMP, DEGCCN2.DEGATS_NEUTRE_MINI AS DEGCCN2_DEGATS_NEUTRE_MINI, DEGCCN2.DEGATS_NEUTRE_MAXI AS DEGCCN2_DEGATS_NEUTRE_MAXI, DEGCCN2.DEGATS_TERRE_MINI AS DEGCCN2_DEGATS_TERRE_MINI, DEGCCN2.DEGATS_TERRE_MAXI AS DEGCCN2_DEGATS_TERRE_MAXI, DEGCCN2.DEGATS_FEU_MINI AS DEGCCN2_DEGATS_FEU_MINI, DEGCCN2.DEGATS_FEU_MAXI AS DEGCCN2_DEGATS_FEU_MAXI, DEGCCN2.DEGATS_EAU_MINI AS DEGCCN2_DEGATS_EAU_MINI, DEGCCN2.DEGATS_EAU_MAXI AS DEGCCN2_DEGATS_EAU_MAXI, DEGCCN2.DEGATS_AIR_MINI AS DEGCCN2_DEGATS_AIR_MINI, DEGCCN2.DEGATS_AIR_MAXI AS DEGCCN2_DEGATS_AIR_MAXI, DEGCCN2.VOLE_NEUTRE_MINI AS DEGCCN2_VOLE_NEUTRE_MINI, DEGCCN2.VOLE_NEUTRE_MAXI AS DEGCCN2_VOLE_NEUTRE_MAXI, DEGCCN2.VOLE_TERRE_MINI AS DEGCCN2_VOLE_TERRE_MINI, DEGCCN2.VOLE_TERRE_MAXI AS DEGCCN2_VOLE_TERRE_MAXI, DEGCCN2.VOLE_FEU_MINI AS DEGCCN2_VOLE_FEU_MINI, DEGCCN2.VOLE_FEU_MAXI AS DEGCCN2_VOLE_FEU_MAXI, DEGCCN2.VOLE_EAU_MINI AS DEGCCN2_VOLE_EAU_MINI, DEGCCN2.VOLE_EAU_MAXI AS DEGCCN2_VOLE_EAU_MAXI, DEGCCN2.VOLE_AIR_MINI AS DEGCCN2_VOLE_AIR_MINI, DEGCCN2.VOLE_AIR_MAXI AS DEGCCN2_VOLE_AIR_MAXI, DEGCCN2.SOINS_MINI AS DEGCCN2_SOINS_MINI, DEGCCN2.SOINS_MAXI AS DEGCCN2_SOINS_MAXI, " + "DEGN3.ID AS DEGN3_ID, DEGN3.TABLE AS DEGN3_TABLE, DEGN3.CHAMP AS DEGN3_CHAMP, DEGN3.DEGATS_NEUTRE_MINI AS DEGN3_DEGATS_NEUTRE_MINI, DEGN3.DEGATS_NEUTRE_MAXI AS DEGN3_DEGATS_NEUTRE_MAXI, DEGN3.DEGATS_TERRE_MINI AS DEGN3_DEGATS_TERRE_MINI, DEGN3.DEGATS_TERRE_MAXI AS DEGN3_DEGATS_TERRE_MAXI, DEGN3.DEGATS_FEU_MINI AS DEGN3_DEGATS_FEU_MINI, DEGN3.DEGATS_FEU_MAXI AS DEGN3_DEGATS_FEU_MAXI, DEGN3.DEGATS_EAU_MINI AS DEGN3_DEGATS_EAU_MINI, DEGN3.DEGATS_EAU_MAXI AS DEGN3_DEGATS_EAU_MAXI, DEGN3.DEGATS_AIR_MINI AS DEGN3_DEGATS_AIR_MINI, DEGN3.DEGATS_AIR_MAXI AS DEGN3_DEGATS_AIR_MAXI, DEGN3.VOLE_NEUTRE_MINI AS DEGN3_VOLE_NEUTRE_MINI, DEGN3.VOLE_NEUTRE_MAXI AS DEGN3_VOLE_NEUTRE_MAXI, DEGN3.VOLE_TERRE_MINI AS DEGN3_VOLE_TERRE_MINI, DEGN3.VOLE_TERRE_MAXI AS DEGN3_VOLE_TERRE_MAXI, DEGN3.VOLE_FEU_MINI AS DEGN3_VOLE_FEU_MINI, DEGN3.VOLE_FEU_MAXI AS DEGN3_VOLE_FEU_MAXI, DEGN3.VOLE_EAU_MINI AS DEGN3_VOLE_EAU_MINI, DEGN3.VOLE_EAU_MAXI AS DEGN3_VOLE_EAU_MAXI, DEGN3.VOLE_AIR_MINI AS DEGN3_VOLE_AIR_MINI, DEGN3.VOLE_AIR_MAXI AS DEGN3_VOLE_AIR_MAXI, DEGN3.SOINS_MINI AS DEGN3_SOINS_MINI, DEGN3.SOINS_MAXI AS DEGN3_SOINS_MAXI, " + "DEGCCN3.ID AS DEGCCN3_ID, DEGCCN3.TABLE AS DEGCCN3_TABLE, DEGCCN3.CHAMP AS DEGCCN3_CHAMP, DEGCCN3.DEGATS_NEUTRE_MINI AS DEGCCN3_DEGATS_NEUTRE_MINI, DEGCCN3.DEGATS_NEUTRE_MAXI AS DEGCCN3_DEGATS_NEUTRE_MAXI, DEGCCN3.DEGATS_TERRE_MINI AS DEGCCN3_DEGATS_TERRE_MINI, DEGCCN3.DEGATS_TERRE_MAXI AS DEGCCN3_DEGATS_TERRE_MAXI, DEGCCN3.DEGATS_FEU_MINI AS DEGCCN3_DEGATS_FEU_MINI, DEGCCN3.DEGATS_FEU_MAXI AS DEGCCN3_DEGATS_FEU_MAXI, DEGCCN3.DEGATS_EAU_MINI AS DEGCCN3_DEGATS_EAU_MINI, DEGCCN3.DEGATS_EAU_MAXI AS DEGCCN3_DEGATS_EAU_MAXI, DEGCCN3.DEGATS_AIR_MINI AS DEGCCN3_DEGATS_AIR_MINI, DEGCCN3.DEGATS_AIR_MAXI AS DEGCCN3_DEGATS_AIR_MAXI, DEGCCN3.VOLE_NEUTRE_MINI AS DEGCCN3_VOLE_NEUTRE_MINI, DEGCCN3.VOLE_NEUTRE_MAXI AS DEGCCN3_VOLE_NEUTRE_MAXI, DEGCCN3.VOLE_TERRE_MINI AS DEGCCN3_VOLE_TERRE_MINI, DEGCCN3.VOLE_TERRE_MAXI AS DEGCCN3_VOLE_TERRE_MAXI, DEGCCN3.VOLE_FEU_MINI AS DEGCCN3_VOLE_FEU_MINI, DEGCCN3.VOLE_FEU_MAXI AS DEGCCN3_VOLE_FEU_MAXI, DEGCCN3.VOLE_EAU_MINI AS DEGCCN3_VOLE_EAU_MINI, DEGCCN3.VOLE_EAU_MAXI AS DEGCCN3_VOLE_EAU_MAXI, DEGCCN3.VOLE_AIR_MINI AS DEGCCN3_VOLE_AIR_MINI, DEGCCN3.VOLE_AIR_MAXI AS DEGCCN3_VOLE_AIR_MAXI, DEGCCN3.SOINS_MINI AS DEGCCN3_SOINS_MINI, DEGCCN3.SOINS_MAXI AS DEGCCN3_SOINS_MAXI, " + "DEGN4.ID AS DEGN4_ID, DEGN4.TABLE AS DEGN4_TABLE, DEGN4.CHAMP AS DEGN4_CHAMP, DEGN4.DEGATS_NEUTRE_MINI AS DEGN4_DEGATS_NEUTRE_MINI, DEGN4.DEGATS_NEUTRE_MAXI AS DEGN4_DEGATS_NEUTRE_MAXI, DEGN4.DEGATS_TERRE_MINI AS DEGN4_DEGATS_TERRE_MINI, DEGN4.DEGATS_TERRE_MAXI AS DEGN4_DEGATS_TERRE_MAXI, DEGN4.DEGATS_FEU_MINI AS DEGN4_DEGATS_FEU_MINI, DEGN4.DEGATS_FEU_MAXI AS DEGN4_DEGATS_FEU_MAXI, DEGN4.DEGATS_EAU_MINI AS DEGN4_DEGATS_EAU_MINI, DEGN4.DEGATS_EAU_MAXI AS DEGN4_DEGATS_EAU_MAXI, DEGN4.DEGATS_AIR_MINI AS DEGN4_DEGATS_AIR_MINI, DEGN4.DEGATS_AIR_MAXI AS DEGN4_DEGATS_AIR_MAXI, DEGN4.VOLE_NEUTRE_MINI AS DEGN4_VOLE_NEUTRE_MINI, DEGN4.VOLE_NEUTRE_MAXI AS DEGN4_VOLE_NEUTRE_MAXI, DEGN4.VOLE_TERRE_MINI AS DEGN4_VOLE_TERRE_MINI, DEGN4.VOLE_TERRE_MAXI AS DEGN4_VOLE_TERRE_MAXI, DEGN4.VOLE_FEU_MINI AS DEGN4_VOLE_FEU_MINI, DEGN4.VOLE_FEU_MAXI AS DEGN4_VOLE_FEU_MAXI, DEGN4.VOLE_EAU_MINI AS DEGN4_VOLE_EAU_MINI, DEGN4.VOLE_EAU_MAXI AS DEGN4_VOLE_EAU_MAXI, DEGN4.VOLE_AIR_MINI AS DEGN4_VOLE_AIR_MINI, DEGN4.VOLE_AIR_MAXI AS DEGN4_VOLE_AIR_MAXI, DEGN4.SOINS_MINI AS DEGN4_SOINS_MINI, DEGN4.SOINS_MAXI AS DEGN4_SOINS_MAXI, " + "DEGCCN4.ID AS DEGCCN4_ID, DEGCCN4.TABLE AS DEGCCN4_TABLE, DEGCCN4.CHAMP AS DEGCCN4_CHAMP, DEGCCN4.DEGATS_NEUTRE_MINI AS DEGCCN4_DEGATS_NEUTRE_MINI, DEGCCN4.DEGATS_NEUTRE_MAXI AS DEGCCN4_DEGATS_NEUTRE_MAXI, DEGCCN4.DEGATS_TERRE_MINI AS DEGCCN4_DEGATS_TERRE_MINI, DEGCCN4.DEGATS_TERRE_MAXI AS DEGCCN4_DEGATS_TERRE_MAXI, DEGCCN4.DEGATS_FEU_MINI AS DEGCCN4_DEGATS_FEU_MINI, DEGCCN4.DEGATS_FEU_MAXI AS DEGCCN4_DEGATS_FEU_MAXI, DEGCCN4.DEGATS_EAU_MINI AS DEGCCN4_DEGATS_EAU_MINI, DEGCCN4.DEGATS_EAU_MAXI AS DEGCCN4_DEGATS_EAU_MAXI, DEGCCN4.DEGATS_AIR_MINI AS DEGCCN4_DEGATS_AIR_MINI, DEGCCN4.DEGATS_AIR_MAXI AS DEGCCN4_DEGATS_AIR_MAXI, DEGCCN4.VOLE_NEUTRE_MINI AS DEGCCN4_VOLE_NEUTRE_MINI, DEGCCN4.VOLE_NEUTRE_MAXI AS DEGCCN4_VOLE_NEUTRE_MAXI, DEGCCN4.VOLE_TERRE_MINI AS DEGCCN4_VOLE_TERRE_MINI, DEGCCN4.VOLE_TERRE_MAXI AS DEGCCN4_VOLE_TERRE_MAXI, DEGCCN4.VOLE_FEU_MINI AS DEGCCN4_VOLE_FEU_MINI, DEGCCN4.VOLE_FEU_MAXI AS DEGCCN4_VOLE_FEU_MAXI, DEGCCN4.VOLE_EAU_MINI AS DEGCCN4_VOLE_EAU_MINI, DEGCCN4.VOLE_EAU_MAXI AS DEGCCN4_VOLE_EAU_MAXI, DEGCCN4.VOLE_AIR_MINI AS DEGCCN4_VOLE_AIR_MINI, DEGCCN4.VOLE_AIR_MAXI AS DEGCCN4_VOLE_AIR_MAXI, DEGCCN4.SOINS_MINI AS DEGCCN4_SOINS_MINI, DEGCCN4.SOINS_MAXI AS DEGCCN4_SOINS_MAXI, " + "DEGN5.ID AS DEGN5_ID, DEGN5.TABLE AS DEGN5_TABLE, DEGN5.CHAMP AS DEGN5_CHAMP, DEGN5.DEGATS_NEUTRE_MINI AS DEGN5_DEGATS_NEUTRE_MINI, DEGN5.DEGATS_NEUTRE_MAXI AS DEGN5_DEGATS_NEUTRE_MAXI, DEGN5.DEGATS_TERRE_MINI AS DEGN5_DEGATS_TERRE_MINI, DEGN5.DEGATS_TERRE_MAXI AS DEGN5_DEGATS_TERRE_MAXI, DEGN5.DEGATS_FEU_MINI AS DEGN5_DEGATS_FEU_MINI, DEGN5.DEGATS_FEU_MAXI AS DEGN5_DEGATS_FEU_MAXI, DEGN5.DEGATS_EAU_MINI AS DEGN5_DEGATS_EAU_MINI, DEGN5.DEGATS_EAU_MAXI AS DEGN5_DEGATS_EAU_MAXI, DEGN5.DEGATS_AIR_MINI AS DEGN5_DEGATS_AIR_MINI, DEGN5.DEGATS_AIR_MAXI AS DEGN5_DEGATS_AIR_MAXI, DEGN5.VOLE_NEUTRE_MINI AS DEGN5_VOLE_NEUTRE_MINI, DEGN5.VOLE_NEUTRE_MAXI AS DEGN5_VOLE_NEUTRE_MAXI, DEGN5.VOLE_TERRE_MINI AS DEGN5_VOLE_TERRE_MINI, DEGN5.VOLE_TERRE_MAXI AS DEGN5_VOLE_TERRE_MAXI, DEGN5.VOLE_FEU_MINI AS DEGN5_VOLE_FEU_MINI, DEGN5.VOLE_FEU_MAXI AS DEGN5_VOLE_FEU_MAXI, DEGN5.VOLE_EAU_MINI AS DEGN5_VOLE_EAU_MINI, DEGN5.VOLE_EAU_MAXI AS DEGN5_VOLE_EAU_MAXI, DEGN5.VOLE_AIR_MINI AS DEGN5_VOLE_AIR_MINI, DEGN5.VOLE_AIR_MAXI AS DEGN5_VOLE_AIR_MAXI, DEGN5.SOINS_MINI AS DEGN5_SOINS_MINI, DEGN5.SOINS_MAXI AS DEGN5_SOINS_MAXI, " + "DEGCCN5.ID AS DEGCCN5_ID, DEGCCN5.TABLE AS DEGCCN5_TABLE, DEGCCN5.CHAMP AS DEGCCN5_CHAMP, DEGCCN5.DEGATS_NEUTRE_MINI AS DEGCCN5_DEGATS_NEUTRE_MINI, DEGCCN5.DEGATS_NEUTRE_MAXI AS DEGCCN5_DEGATS_NEUTRE_MAXI, DEGCCN5.DEGATS_TERRE_MINI AS DEGCCN5_DEGATS_TERRE_MINI, DEGCCN5.DEGATS_TERRE_MAXI AS DEGCCN5_DEGATS_TERRE_MAXI, DEGCCN5.DEGATS_FEU_MINI AS DEGCCN5_DEGATS_FEU_MINI, DEGCCN5.DEGATS_FEU_MAXI AS DEGCCN5_DEGATS_FEU_MAXI, DEGCCN5.DEGATS_EAU_MINI AS DEGCCN5_DEGATS_EAU_MINI, DEGCCN5.DEGATS_EAU_MAXI AS DEGCCN5_DEGATS_EAU_MAXI, DEGCCN5.DEGATS_AIR_MINI AS DEGCCN5_DEGATS_AIR_MINI, DEGCCN5.DEGATS_AIR_MAXI AS DEGCCN5_DEGATS_AIR_MAXI, DEGCCN5.VOLE_NEUTRE_MINI AS DEGCCN5_VOLE_NEUTRE_MINI, DEGCCN5.VOLE_NEUTRE_MAXI AS DEGCCN5_VOLE_NEUTRE_MAXI, DEGCCN5.VOLE_TERRE_MINI AS DEGCCN5_VOLE_TERRE_MINI, DEGCCN5.VOLE_TERRE_MAXI AS DEGCCN5_VOLE_TERRE_MAXI, DEGCCN5.VOLE_FEU_MINI AS DEGCCN5_VOLE_FEU_MINI, DEGCCN5.VOLE_FEU_MAXI AS DEGCCN5_VOLE_FEU_MAXI, DEGCCN5.VOLE_EAU_MINI AS DEGCCN5_VOLE_EAU_MINI, DEGCCN5.VOLE_EAU_MAXI AS DEGCCN5_VOLE_EAU_MAXI, DEGCCN5.VOLE_AIR_MINI AS DEGCCN5_VOLE_AIR_MINI, DEGCCN5.VOLE_AIR_MAXI AS DEGCCN5_VOLE_AIR_MAXI, DEGCCN5.SOINS_MINI AS DEGCCN5_SOINS_MINI, DEGCCN5.SOINS_MAXI AS DEGCCN5_SOINS_MAXI, " + "DEGN6.ID AS DEGN6_ID, DEGN6.TABLE AS DEGN6_TABLE, DEGN6.CHAMP AS DEGN6_CHAMP, DEGN6.DEGATS_NEUTRE_MINI AS DEGN6_DEGATS_NEUTRE_MINI, DEGN6.DEGATS_NEUTRE_MAXI AS DEGN6_DEGATS_NEUTRE_MAXI, DEGN6.DEGATS_TERRE_MINI AS DEGN6_DEGATS_TERRE_MINI, DEGN6.DEGATS_TERRE_MAXI AS DEGN6_DEGATS_TERRE_MAXI, DEGN6.DEGATS_FEU_MINI AS DEGN6_DEGATS_FEU_MINI, DEGN6.DEGATS_FEU_MAXI AS DEGN6_DEGATS_FEU_MAXI, DEGN6.DEGATS_EAU_MINI AS DEGN6_DEGATS_EAU_MINI, DEGN6.DEGATS_EAU_MAXI AS DEGN6_DEGATS_EAU_MAXI, DEGN6.DEGATS_AIR_MINI AS DEGN6_DEGATS_AIR_MINI, DEGN6.DEGATS_AIR_MAXI AS DEGN6_DEGATS_AIR_MAXI, DEGN6.VOLE_NEUTRE_MINI AS DEGN6_VOLE_NEUTRE_MINI, DEGN6.VOLE_NEUTRE_MAXI AS DEGN6_VOLE_NEUTRE_MAXI, DEGN6.VOLE_TERRE_MINI AS DEGN6_VOLE_TERRE_MINI, DEGN6.VOLE_TERRE_MAXI AS DEGN6_VOLE_TERRE_MAXI, DEGN6.VOLE_FEU_MINI AS DEGN6_VOLE_FEU_MINI, DEGN6.VOLE_FEU_MAXI AS DEGN6_VOLE_FEU_MAXI, DEGN6.VOLE_EAU_MINI AS DEGN6_VOLE_EAU_MINI, DEGN6.VOLE_EAU_MAXI AS DEGN6_VOLE_EAU_MAXI, DEGN6.VOLE_AIR_MINI AS DEGN6_VOLE_AIR_MINI, DEGN6.VOLE_AIR_MAXI AS DEGN6_VOLE_AIR_MAXI, DEGN6.SOINS_MINI AS DEGN6_SOINS_MINI, DEGN6.SOINS_MAXI AS DEGN6_SOINS_MAXI, " + "DEGCCN6.ID AS DEGCCN6_ID, DEGCCN6.TABLE AS DEGCCN6_TABLE, DEGCCN6.CHAMP AS DEGCCN6_CHAMP, DEGCCN6.DEGATS_NEUTRE_MINI AS DEGCCN6_DEGATS_NEUTRE_MINI, DEGCCN6.DEGATS_NEUTRE_MAXI AS DEGCCN6_DEGATS_NEUTRE_MAXI, DEGCCN6.DEGATS_TERRE_MINI AS DEGCCN6_DEGATS_TERRE_MINI, DEGCCN6.DEGATS_TERRE_MAXI AS DEGCCN6_DEGATS_TERRE_MAXI, DEGCCN6.DEGATS_FEU_MINI AS DEGCCN6_DEGATS_FEU_MINI, DEGCCN6.DEGATS_FEU_MAXI AS DEGCCN6_DEGATS_FEU_MAXI, DEGCCN6.DEGATS_EAU_MINI AS DEGCCN6_DEGATS_EAU_MINI, DEGCCN6.DEGATS_EAU_MAXI AS DEGCCN6_DEGATS_EAU_MAXI, DEGCCN6.DEGATS_AIR_MINI AS DEGCCN6_DEGATS_AIR_MINI, DEGCCN6.DEGATS_AIR_MAXI AS DEGCCN6_DEGATS_AIR_MAXI, DEGCCN6.VOLE_NEUTRE_MINI AS DEGCCN6_VOLE_NEUTRE_MINI, DEGCCN6.VOLE_NEUTRE_MAXI AS DEGCCN6_VOLE_NEUTRE_MAXI, DEGCCN6.VOLE_TERRE_MINI AS DEGCCN6_VOLE_TERRE_MINI, DEGCCN6.VOLE_TERRE_MAXI AS DEGCCN6_VOLE_TERRE_MAXI, DEGCCN6.VOLE_FEU_MINI AS DEGCCN6_VOLE_FEU_MINI, DEGCCN6.VOLE_FEU_MAXI AS DEGCCN6_VOLE_FEU_MAXI, DEGCCN6.VOLE_EAU_MINI AS DEGCCN6_VOLE_EAU_MINI, DEGCCN6.VOLE_EAU_MAXI AS DEGCCN6_VOLE_EAU_MAXI, DEGCCN6.VOLE_AIR_MINI AS DEGCCN6_VOLE_AIR_MINI, DEGCCN6.VOLE_AIR_MAXI AS DEGCCN6_VOLE_AIR_MAXI, DEGCCN6.SOINS_MINI AS DEGCCN6_SOINS_MINI, DEGCCN6.SOINS_MAXI AS DEGCCN6_SOINS_MAXI " + "FROM SORTS AS S " + "LEFT JOIN NIVEAUX_SORTS AS N1 ON N1.ID = S.NIVEAU_1 " + "LEFT JOIN NIVEAUX_SORTS AS N2 ON N2.ID = S.NIVEAU_2 " + "LEFT JOIN NIVEAUX_SORTS AS N3 ON N3.ID = S.NIVEAU_3 " + "LEFT JOIN NIVEAUX_SORTS AS N4 ON N4.ID = S.NIVEAU_4 " + "LEFT JOIN NIVEAUX_SORTS AS N5 ON N5.ID = S.NIVEAU_5 " + "LEFT JOIN NIVEAUX_SORTS AS N6 ON N6.ID = S.NIVEAU_6 " + "LEFT JOIN DEGATS AS DEGN1 ON DEGN1.ID = N1.DEGATS " + "LEFT JOIN DEGATS AS DEGCCN1 ON DEGCCN1.ID = N1.DEGATS_CC " + "LEFT JOIN DEGATS AS DEGN2 ON DEGN2.ID = N2.DEGATS " + "LEFT JOIN DEGATS AS DEGCCN2 ON DEGCCN2.ID = N2.DEGATS_CC " + "LEFT JOIN DEGATS AS DEGN3 ON DEGN3.ID = N3.DEGATS " + "LEFT JOIN DEGATS AS DEGCCN3 ON DEGCCN3.ID = N3.DEGATS_CC " + "LEFT JOIN DEGATS AS DEGN4 ON DEGN4.ID = N4.DEGATS " + "LEFT JOIN DEGATS AS DEGCCN4 ON DEGCCN4.ID = N4.DEGATS_CC " + "LEFT JOIN DEGATS AS DEGN5 ON DEGN5.ID = N5.DEGATS " + "LEFT JOIN DEGATS AS DEGCCN5 ON DEGCCN5.ID = N5.DEGATS_CC " + "LEFT JOIN DEGATS AS DEGN6 ON DEGN6.ID = N6.DEGATS " + "LEFT JOIN DEGATS AS DEGCCN6 ON DEGCCN6.ID = N6.DEGATS_CC " + "WHERE S.CLASSE=" + classe + " ORDER BY S.ID ASC");
			ResultSet res = req.getResultats();
			while(res.next())
			{
				Sort sort = new Sort(res.getString("NOM"));
				sort.setId(res.getInt("ID"));
				sort.setNature(Sort.NatureSortsFlags.getType(res.getString("NATURE")));

				for(int i = 1; i <= 6; i++)
				{
					sort.set(i, "PA", res.getString("N" + i + "_PA"));
					sort.set(i, "CC", res.getString("N" + i + "_CC"));
					sort.set(i, "EC", res.getString("N" + i + "_EC"));
					sort.set(i, "Degats", new Degats().charger(res, "DEGN" + i));
					sort.set(i, "DegatsCC", new Degats().charger(res, "DEGCCN" + i));
				}

				sorts.add(sort);
			}

			return sorts;
		}
		catch(SQLException exception)
		{
			ASQL.erreur(exception);
			return null;
		}
	}
}