;             
CREATE USER IF NOT EXISTS ADMINISTRATEUR PASSWORD '' ADMIN;   
CREATE USER IF NOT EXISTS JDOFUSCALC PASSWORD '' ADMIN;       
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E51BC259_C9DA_4B53_B056_6C16431223C4 START WITH 169 BELONGS_TO_TABLE;  
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_5A993440_CA8C_4EEF_BFB5_4D97965B37D5 START WITH 103 BELONGS_TO_TABLE;  
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4FE88599_FBC6_4A7C_BBC4_57ABFB35E3F2 START WITH 221 BELONGS_TO_TABLE;  
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_65562A30_8E0E_4B1E_9FE3_58FB830669F3 START WITH 69 BELONGS_TO_TABLE;   
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_11380FCE_F7C3_47E4_B77B_39402B9421F1 START WITH 628 BELONGS_TO_TABLE;  
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FDBE5C9F_2209_42D7_BAA3_116B40F88A1F START WITH 1788 BELONGS_TO_TABLE; 
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A392F9B1_CEE1_4023_9FF2_5BB4FD80AD3D START WITH 195 BELONGS_TO_TABLE;  
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F3E06E09_31FF_457D_8A6C_794AFD9255A0 START WITH 203 BELONGS_TO_TABLE;  
CREATE CACHED TABLE PUBLIC.DEGATS(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_11380FCE_F7C3_47E4_B77B_39402B9421F1) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_11380FCE_F7C3_47E4_B77B_39402B9421F1 SELECTIVITY 100,
    TABLE VARCHAR(100) SELECTIVITY 1,
    CHAMP VARCHAR(100) SELECTIVITY 1,
    DEGATS_NEUTRE_MINI INT SELECTIVITY 2,
    DEGATS_NEUTRE_MAXI INT SELECTIVITY 3,
    DEGATS_TERRE_MINI INT SELECTIVITY 2,
    DEGATS_TERRE_MAXI INT SELECTIVITY 3,
    DEGATS_FEU_MINI INT SELECTIVITY 1,
    DEGATS_FEU_MAXI INT SELECTIVITY 2,
    DEGATS_EAU_MINI INT SELECTIVITY 1,
    DEGATS_EAU_MAXI INT SELECTIVITY 2,
    DEGATS_AIR_MINI INT SELECTIVITY 2,
    DEGATS_AIR_MAXI INT SELECTIVITY 2,
    VOLE_NEUTRE_MINI INT SELECTIVITY 1,
    VOLE_NEUTRE_MAXI INT SELECTIVITY 1,
    VOLE_TERRE_MINI INT SELECTIVITY 1,
    VOLE_TERRE_MAXI INT SELECTIVITY 1,
    VOLE_FEU_MINI INT SELECTIVITY 1,
    VOLE_FEU_MAXI INT SELECTIVITY 1,
    VOLE_EAU_MINI INT SELECTIVITY 1,
    VOLE_EAU_MAXI INT SELECTIVITY 1,
    VOLE_AIR_MINI INT SELECTIVITY 1,
    VOLE_AIR_MAXI INT SELECTIVITY 1,
    SOINS_MINI INT SELECTIVITY 1,
    SOINS_MAXI INT SELECTIVITY 1
);               
-- 132 +/- SELECT COUNT(*) FROM PUBLIC.DEGATS;
CREATE CACHED TABLE PUBLIC.PERSONNAGES(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F3E06E09_31FF_457D_8A6C_794AFD9255A0) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F3E06E09_31FF_457D_8A6C_794AFD9255A0,
    NOM VARCHAR(100),
    NOM_PERSO VARCHAR(100),
    NIVEAU INT,
    CLASSE INT,
    SEXE CHAR(1),
    ALIGNEMENT INT,
    GRADE INT,
    NIVEAU_ALIGNEMENT INT,
    SPE_ALIGNEMENT INT,
    MAITRISE_ARCS INT DEFAULT 0,
    MAITRISE_BAGUETTES INT DEFAULT 0,
    MAITRISE_BATONS INT DEFAULT 0,
    MAITRISE_DAGUES INT DEFAULT 0,
    MAITRISE_EPEES INT DEFAULT 0,
    MAITRISE_HACHES INT DEFAULT 0,
    MAITRISE_MARTEAUX INT DEFAULT 0,
    MAITRISE_PELLES INT DEFAULT 0,
    VITALITE INT,
    SAGESSE INT,
    FORCE INT,
    INTELLIGENCE INT,
    CHANCE INT,
    AGILITE INT
);         
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.PERSONNAGES;             
CREATE CACHED TABLE PUBLIC.DOFUS(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_5A993440_CA8C_4EEF_BFB5_4D97965B37D5) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_5A993440_CA8C_4EEF_BFB5_4D97965B37D5,
    TYPE INT,
    NOM VARCHAR(100),
    NIVEAU INT,
    EFFETS INT
);        
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.DOFUS;   
CREATE CACHED TABLE PUBLIC.EFFETS(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_FDBE5C9F_2209_42D7_BAA3_116B40F88A1F) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FDBE5C9F_2209_42D7_BAA3_116B40F88A1F SELECTIVITY 100,
    TABLE VARCHAR(100) SELECTIVITY 1,
    CHAMP VARCHAR(100) SELECTIVITY 1,
    VIE DOUBLE,
    PA DOUBLE,
    PM DOUBLE,
    PO DOUBLE,
    INITIATIVE DOUBLE,
    PP DOUBLE,
    VITALITE DOUBLE,
    SAGESSE DOUBLE,
    FORCE DOUBLE,
    INTELLIGENCE DOUBLE,
    CHANCE DOUBLE,
    AGILITE DOUBLE,
    DOMMAGES DOUBLE,
    POURCENTAGES_DOMMAGES DOUBLE,
    PIEGES DOUBLE,
    POURCENTAGES_PIEGES DOUBLE,
    CC DOUBLE,
    SOINS DOUBLE,
    CREATURES_INVOCABLES DOUBLE,
    PODS DOUBLE,
    RESISTANCE_MAGIQUE DOUBLE,
    RESISTANCE_PHYSIQUE DOUBLE,
    RESISTANCE_NEUTRE DOUBLE,
    RESISTANCE_TERRE DOUBLE,
    RESISTANCE_FEU DOUBLE,
    RESISTANCE_EAU DOUBLE,
    RESISTANCE_AIR DOUBLE,
    POURCENTAGES_RESISTANCE_NEUTRE DOUBLE,
    POURCENTAGES_RESISTANCE_TERRE DOUBLE,
    POURCENTAGES_RESISTANCE_FEU DOUBLE,
    POURCENTAGES_RESISTANCE_EAU DOUBLE,
    POURCENTAGES_RESISTANCE_AIR DOUBLE,
    RENVOIS DOUBLE,
    EC DOUBLE,
    RESISTANCE_NEUTRE_COMBATTANTS DOUBLE,
    RESISTANCE_TERRE_COMBATTANTS DOUBLE,
    RESISTANCE_FEU_COMBATTANTS DOUBLE,
    RESISTANCE_EAU_COMBATTANTS DOUBLE,
    RESISTANCE_AIR_COMBATTANTS DOUBLE,
    POURCENTAGES_RESISTANCE_NEUTRE_COMBATTANTS DOUBLE,
    POURCENTAGES_RESISTANCE_TERRE_COMBATTANTS DOUBLE,
    POURCENTAGES_RESISTANCE_FEU_COMBATTANTS DOUBLE,
    POURCENTAGES_RESISTANCE_EAU_COMBATTANTS DOUBLE,
    POURCENTAGES_RESISTANCE_AIR_COMBATTANTS DOUBLE
);        
-- 271 +/- SELECT COUNT(*) FROM PUBLIC.EFFETS;
CREATE CACHED TABLE PUBLIC.GROUPES_OBJETS(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_65562A30_8E0E_4B1E_9FE3_58FB830669F3) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_65562A30_8E0E_4B1E_9FE3_58FB830669F3,
    NOM VARCHAR(100),
    AMULETTE INT,
    ANNEAU_G INT,
    ANNEAU_D INT,
    CEINTURE INT,
    BOTTES INT,
    COIFFE INT,
    CAPE INT,
    FAMILIER INT,
    MONTURE INT,
    BOUCLIER INT,
    ARME INT,
    DOFUS_CAWOTTE INT,
    DOFUS_OCRE INT,
    DOFUS_VULBIS INT,
    DOFUS_EMERAUDE INT,
    DOFUS_POURPRE INT,
    DOFUS_KALIPTUS INT,
    DOFAWA INT
);            
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.GROUPES_OBJETS;          
CREATE CACHED TABLE PUBLIC.ARMES(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_E51BC259_C9DA_4B53_B056_6C16431223C4) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E51BC259_C9DA_4B53_B056_6C16431223C4 SELECTIVITY 100,
    TYPE INT SELECTIVITY 1,
    NOM VARCHAR(100) SELECTIVITY 94,
    DESCRIPTION CLOB SELECTIVITY 67,
    NIVEAU INT SELECTIVITY 19,
    CONDITIONS OTHER,
    PANOPLIE INT SELECTIVITY 6,
    PA INT SELECTIVITY 1,
    PO INT SELECTIVITY 1,
    CC INT SELECTIVITY 2,
    BONUS_CC INT SELECTIVITY 2,
    EC INT SELECTIVITY 2,
    DEGATS_1 INT SELECTIVITY 100,
    DEGATS_2 INT SELECTIVITY 23,
    DEGATS_3 INT SELECTIVITY 6,
    DEGATS_4 INT SELECTIVITY 3,
    DEGATS_5 INT SELECTIVITY 1,
    EFFETS INT SELECTIVITY 100,
    EFFETS_AUTRE CLOB SELECTIVITY 1
); 
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.ARMES;   
CREATE CACHED TABLE PUBLIC.EQUIPEMENTS(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_4FE88599_FBC6_4A7C_BBC4_57ABFB35E3F2) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4FE88599_FBC6_4A7C_BBC4_57ABFB35E3F2 SELECTIVITY 100,
    TYPE INT SELECTIVITY 1,
    NOM VARCHAR(100) SELECTIVITY 100,
    DESCRIPTION CLOB SELECTIVITY 88,
    NIVEAU INT SELECTIVITY 16,
    CONDITIONS OTHER,
    PANOPLIE INT SELECTIVITY 11,
    EFFETS INT SELECTIVITY 100,
    EFFETS_AUTRE CLOB SELECTIVITY 1
);    
-- 13 +/- SELECT COUNT(*) FROM PUBLIC.EQUIPEMENTS;            
CREATE CACHED TABLE PUBLIC.MONTURES(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A392F9B1_CEE1_4023_9FF2_5BB4FD80AD3D) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A392F9B1_CEE1_4023_9FF2_5BB4FD80AD3D,
    RACE INT,
    NOM VARCHAR(100),
    NIVEAU_MONTURE INT,
    NIVEAU INT,
    CONDITIONS OTHER,
    EFFETS INT
);       
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.MONTURES;
CREATE CACHED TABLE PUBLIC.NIVEAUX_SORTS(
    ID_PERSONNAGE INT,
    NOM_SORT VARCHAR(200),
    NIVEAU_SORT INT
);            
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.NIVEAUX_SORTS;           
ALTER TABLE PUBLIC.EFFETS ADD CONSTRAINT PUBLIC.CONSTRAINT_79 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.MONTURES ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);               
ALTER TABLE PUBLIC.DEGATS ADD CONSTRAINT PUBLIC.CONSTRAINT_77 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.GROUPES_OBJETS ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);         
ALTER TABLE PUBLIC.DOFUS ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);  
ALTER TABLE PUBLIC.ARMES ADD CONSTRAINT PUBLIC.CONSTRAINT_3B PRIMARY KEY(ID); 
ALTER TABLE PUBLIC.PERSONNAGES ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);            
ALTER TABLE PUBLIC.EQUIPEMENTS ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(ID);            
