TRUNCATE TABLE ARMES;
ALTER TABLE ARMES ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE DOFUS;
ALTER TABLE DOFUS ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE DEGATS;
ALTER TABLE DEGATS ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE EFFETS;
ALTER TABLE EFFETS ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE PERSONNAGES ;
ALTER TABLE PERSONNAGES ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE GROUPES_OBJETS;
ALTER TABLE GROUPES_OBJETS ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE EQUIPEMENTS;
ALTER TABLE EQUIPEMENTS ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE MONTURES;
ALTER TABLE MONTURES ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE NIVEAUX_SORTS ;